version: '3.8'

services:
  file-service:
    build: .
    image: file-service:latest
    container_name: file-service
    ports:
      - '8080:8080'
    volumes:
      - ./data:/app/data
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:9.0.0
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
