apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'alerts@example.com'
      smtp_auth_username: 'nmtherethere@gmail.com'
      smtp_auth_password: 'giprpsilvnhamakm'
      smtp_require_tls: true

    route:
      receiver: 'default'

    receivers:
      - name: 'default'
        email_configs:
          - to: 'nmtherethere@gmail.com'
            send_resolved: true
