apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-rules
data:
  alert-rules.yml: |
    groups:
      - name: file-service-alerts
        interval: 15s
        rules:
          - alert: FileServiceDown
            expr: up{job="file-service"} == 0
            for: 30s
            labels:
              severity: critical
            annotations:
              summary: "File service is down"
              description: "The file-service has been unreachable for more than 30s."

          - alert: HighRequestLatency
            expr: http_server_requests_seconds_max{job="file-service"} > 2
            for: 1m
            labels:
              severity: warning
            annotations:
              summary: "High request latency"
              description: "File-service requests are taking longer than 2 seconds."
